# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.CharField(blank=True, default='http://10.5.5.9', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('discovered_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('image_count', models.IntegerField(blank=True, default=None)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='tldl.Camera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255)),
                ('discovered_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('file', models.FileField(blank=True, default='', max_length=255, upload_to='')),
                ('shot_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tldl.Camera')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tldl.Directory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(choices=[('640x480', '640x480'), ('320x240', '320x240'), ('160x120', '160x120')], max_length=32)),
                ('generated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('file', models.FileField(blank=True, default='', max_length=255, upload_to='')),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='tldl.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
