# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tldl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('camera', 'path')]),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnail',
            unique_together=set([('image', 'size')]),
        ),
    ]
